<a href="https://colab.research.google.com/github/Phuntsok68/demo-repo/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np
# array
import matplotlib.pyplot as plt
# charts and graphs
import pandas as pd
# working with datasets

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
#read_csv() function takes a path to a CSV file and reads the data into a Pandas DataFrame object.
X = dataset.iloc[:, :-1].values
#                rows columns
#  iloc means locate index
# features or independent variables
y = dataset.iloc[:, -1].values
# dependent variables


In [4]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [6]:
# deleting the observation
# replacing with the average of the datas

from sklearn.impute import SimpleImputer
#            module         class
# SimpleImputer is a class from the scikit-learn library in Python that is used for imputing missing values in a dataset. It provides a simple strategy to impute missing values, such as filling them with the mean or median of the column.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
#       method that connects the imputer with the features of matrix
X[:, 1:3] = imputer.transform(X[:, 1:3])
#                    replace/change
                  #  return the updated matrix so save in the variable
                  

In [7]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [8]:
# categorical data into numerical data
# one hot encoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#                                                                  index  don't change the remaining columns
#  one hot encoding is a specific method to encode the catgorical data into numerical datas
#                                     It can also be used to transform non-numerical labels (as long as they are hashable and comparable) to numerical labels.
X = np.array(ct.fit_transform(X))
#               return updated values
#                fit_transform apply fit and transform 

In [9]:
print(X)
# each row encode the specific country and there is no numerical order

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Use LabelEncoder when there are only two possible values of a categorical features. For example, features having value such as yes or no. Or, maybe, gender feature when there are only two possible values including male or female
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

In [ ]:
print(X_test)

In [ ]:
print(y_train)

In [ ]:
print(y_test)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
# to scale a features in order to avoid dominance and to make them roughly similar
# standardisation (-3,+3)and normalisation (0,1)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

In [ ]:
print(X_test)